### ISSUE TITLE
EventGridMiddleware.IsNotificationRequest: content-type validation not working if charset is defined

### ISSUE THREAD

**Issue by SimonLuckenuik** [pmcilreavy/AzureEventGridSimulator#10]
If the content-type contains the charset, the validation will fail and request will be rejected.
Example: Content-Type: application/json; charset=utf-8

Ref: https://www.w3.org/International/articles/http-charset/index#charset

The charset is accepted by Event Grid cloud service.

**Comment by pmcilreavy** [comment]
Fixed in 1.0.53.
