### ISSUE TITLE
Running the emulator on Docker

### ISSUE THREAD

**Issue by rrr-michael-aquilina** [pmcilreavy/AzureEventGridSimulator#106]
Hi all,

I am wondering if anyone has had luck running the emulator on docker? I am running docker on WSL2 am have been facing issues connecting to the endpoints.

Using the postman collection provided, I receive Error: connect ECONNREFUSED 127.0.0.1:60101. I have run the command to generate the certificates but am still facing issues.

Is there a more detailed example anywhere?

**Comment by AndreyBespamyatnov** [comment]
Hello @rrr-michael-aquilina  I did that, and all works fine on my side. 

1. copy the source to the **AzureEventGridSimulator** folder
2. here is my docker file:
```
FROM mcr.microsoft.com/dotnet/sdk:3.1 as build
WORKDIR /source

# restores nuget packages
COPY AzureEventGridSimulator/src/AzureEventGridSimulator/*.csproj .
RUN dotnet restore

# copy source code
COPY AzureEventGridSimulator/src/AzureEventGridSimulator .

# builds the source code using the SDK
RUN dotnet publish -c release -o /app

# runs the deployable on a separate image
# that is shipped with the .NET Runtime
FROM mcr.microsoft.com/dotnet/aspnet:3.1
WORKDIR /app
COPY --from=build /app .
COPY YOUR_CERT.com.pfx .
COPY appsettings.json .

USER ContainerAdministrator
ENV ASPNETCORE_Kestrel__Certificates__Default__Password="CERT_PASSWORD"
ENV ASPNETCORE_Kestrel__Certificates__Default__Path="C:\\app\\YOUR_CERT.com.pfx"
ENV ASPNETCORE_ENVIRONMENT=Development

ENTRYPOINT ["AzureEventGridSimulator.exe"]
```
3. create example.appsettings.json and add your settings
4. build your image: 
`docker build -t eventgrid_image_name_tag .`
5. run container, you can specify the configuration file, you have to map you config file. ${PWD} - your curretn folder. C:\temp\ - folder inside the container:
```
docker run -dit --rm -v ${PWD}:C:\temp\ --name eventgrid-dev eventgrid_image_name_tag --entrypoint AzureEventGridSimulator.exe --ConfigFile=C:\temp\appsettings.json
```

**Comment by AndreyBespamyatnov** [comment]
> Thanks @AndreyBespamyatnov,
> 
> I'm using the image from docker hub.

Yeah, sounds like the SSL issue, have you checked that you added your certs to the trust store in the docker and locally?

**Comment by rrr-michael-aquilina** [comment]
I have tried to create the cert and add to docker but still no luck. 

This is what I tried so far.

1. Manually generate self-signed cert

![image](https://user-images.githubusercontent.com/79424711/176578258-fd9aff78-0445-4243-a312-741ee2d5db99.png)

2. Added to /usr/local/share/ca-certificates/

3. Ran update-ca-certificates

![image](https://user-images.githubusercontent.com/79424711/176578563-d0b7b8dd-b437-4ad0-ab7a-4ba2bbe1d214.png)

After doing the above and running curl CMD, i still get the same connection refused error.

`
![image](https://user-images.githubusercontent.com/79424711/176578667-41416984-da0a-4a5d-9541-7e9278e9287c.png)
`

Am I doing something obviously wrong?

**Comment by pmcilreavy** [comment]
Hi, can you try this...

1) In Docker... open the terminal for the running container...
<img width="973" alt="image" src="https://user-images.githubusercontent.com/3075792/178090219-96c6ff9a-ed42-4e5a-af03-ffe9512f54be.png">

2) navigate to the folder containing your cert (in the default example script this will be the `aegs` folder...

<img width="577" alt="image" src="https://user-images.githubusercontent.com/3075792/178090277-a1982110-7a84-4763-a201-65c391dccff5.png">

3) when you `ls` in that folder you should see your certificate there. If you don't then something has gone wrong with the volume binding. The simulator won't be able to find your cert and therefore can't accept any SSL connections.

In your example it looks like you are mounting volume `.` but then the certificate you are referencing is in `/usr/local/share/ca-certificates/` - is this folder definitely being shared? perhaps navigate to this folder and check it contains the cert as you expect.

**Comment by michalpawlik93** [comment]
Hey,
I had same issue and followed @pmcilreavy post to investigate if my cert
is inside docker. That was handy. Once cert appeared inside docker, all started working. 

I see differences between our configurations. Take a look, it may help you:

1. Try to change volumes to:
    volumes:
      - ./docker:/aegs:ro

2. Env variable to:
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/aegs/azureEventGridSimulator.pfx 
3. Execute command to get your cert:
 dotnet dev-certs https --export-path ./docker/azureEventGridSimulator.pfx --password
