### ISSUE TITLE
Too high log level for filtered out events

### ISSUE THREAD

**Issue by M0ns1gn0r** [pmcilreavy/AzureEventGridSimulator#17]
https://github.com/pmcilreavy/AzureEventGridSimulator/blob/ac2ce052c96c3b6a6ac636ce0c90e3659351d6e3/src/AzureEventGridSimulator/Domain/Commands/SendNotificationEventsToSubscriberCommandHandler.cs#L76-L79

I have two questions regarding this line:
1. On our project we quite heavily use the filtering functionality based on event type. This means, we have tens on subscriptions different only in `includedEventTypes`. So a filtered out event is not an abnormal situation at all, it's probably even not worth the *Information* level. I would suggest to reduce the logging level to *Debug*, what do you think?
1. But there are situation when we forget to create a subscription and an event really gets ignored. Would it be possible to emit a *Warning* when an event was filtered out of all subscriptions?

**Comment by pmcilreavy** [comment]
This should be resolved now in `master`

**Comment by M0ns1gn0r** [comment]
Thanks @pmcilreavy.  I had a look at #19, the warning is emitted when a Topic has no subscribers but there seems to be no warning emitted when *all subscribers* have filtered out the event.

**Comment by pmcilreavy** [comment]
Ah yeah. I think I slightly misunderstood you. I've added warnings for when there are no subscribers or all subscribers are disabled.
So I'll add another for when the is at least 1 active subscriber and they all filter out an event (i.e the event was essentially dropped).
