### ISSUE TITLE
No validation event handshake?

### ISSUE THREAD

**Issue by Barsonax** [pmcilreavy/AzureEventGridSimulator#4]
First of all thanks for making this simulator!

I believe the validation event handshake is missing from this simulator: https://docs.microsoft.com/en-us/azure/event-grid/security-authentication

**Comment by pmcilreavy** [comment]
Hmm yes. Good point. Although, I have not yet found a need to have this feature in the simulator. Could you describe the scenario you have where you are finding you need this feature? This will help me come up with the solution and tests. Thanks.

**Comment by Barsonax** [comment]
Iam working on a complex application that also has to handle some eventgrid events. When testing thise locally I want to be sure it handles eventgrid correctly.

Thus it helps if the simulator also implements the validation handshake the same way the real eventgrid does it.

**Comment by pmcilreavy** [comment]
I just pushed some changes to `master` which include initial support for subscription validation. I'm still refining the code but the functionality is basically working. Anyway if you want to try it out, let me know what you think.

When the simulator starts up it will send the validation event to each subscriber. If it fails you can still validate the subscription using the validation url which will be displayed in the console. A subscription will not be sent events until it's validated successfully.

I will look at enhancing the features further: e.g. Adding a new setting to disabled/enable the validation check on each subscription.

**Comment by Barsonax** [comment]
Tested it, found a bug in my applicationx fixed it and now it works.
