### ISSUE TITLE
Add docker image

### ISSUE THREAD

**Issue by Barsonax** [pmcilreavy/AzureEventGridSimulator#5]
Would be useful if there was a docker image for this. In my case iam running a complex application consisting of multiple containers and I also need to test functionality that depends on eventgrid.

If you like I could setup the stuff needed to build a docker image.

**Comment by AndreyBespamyatnov** [comment]
I made a PR, will update soon it, https://github.com/pmcilreavy/AzureEventGridSimulator/pull/2

**Comment by pmcilreavy** [comment]
I've made some steps toward better Docker support and a hosted docker image here https://hub.docker.com/repository/docker/pmcilreavy/azureeventgridsimulator

I need to still update the README documentation to reflect this but you can see a Dockerfile and docker-compose.yml file (as well as 2 powershell files) that show how you could run the image and pass config to it.

**Comment by pmcilreavy** [comment]
Gonna close this now as there is now a docker image at https://hub.docker.com/r/pmcilreavy/azureeventgridsimulator and there is also a `Dockerfile` and `docker-compose.yml` file in the repo.
