### ISSUE TITLE
Local Storage Emulator: Blob upload-to-Event Grid Message-to-Storage Queue possible?

### ISSUE THREAD

**Issue by SeaDude** [pmcilreavy/AzureEventGridSimulator#59]
Hello,

Is there a way to use `AzureEventGridSimulator` to simulate an EventGrid message upon blob upload to a local Azure Storage Emulator? Then have this EG message write to the Queue Storage running on the same emulator?

**Example:**
- Upload blob to container in local Azure Storage Emulator
- `AzureEventGridSimulator` simulates an EventGrid message
- `AzureEventGridSimulator` writes message to local Azure Storage Emulator Queue Storage

If so, could you provide a sample of the `settings.json` for such a setup? 

Thank you

**Comment by pmcilreavy** [comment]
I've not found any way to do this yet. But for testing purposes, you could just write your own little console app that polled your storage container for new blobs and then construct your own events and send them to the simulator.
