### ISSUE TITLE
Unit test project currently not compiling

### ISSUE THREAD

**Issue by uprightbass360** [pmcilreavy/AzureEventGridSimulator#6]
* Error	The call is ambiguous between the following methods or properties: 'Assert.Throws<T>(Action)' and 'Assert.Throws<T>(Func<Task>)'	UnitTests	C:\repos\pmcilreavy\AzureEventGridSimulator\src\UnitTests\Filtering\AdvancedFilterValidationTests.cs
* Error	The call is ambiguous between the following methods or properties: 'Assert.Throws<T>(Action)' and 'Assert.Throws<T>(Func<Task>)'	UnitTests	C:\repos\pmcilreavy\AzureEventGridSimulator\src\UnitTests\Filtering\AdvancedFilterValidationTests.cs
* Error	The call is ambiguous between the following methods or properties: 'Assert.Throws<T>(Action)' and 'Assert.Throws<T>(Func<Task>)'	UnitTests	C:\repos\pmcilreavy\AzureEventGridSimulator\src\UnitTests\Filtering\AdvancedFilterValidationTests.cs
* Error	The call is ambiguous between the following methods or properties: 'Assert.Throws<T>(Action)' and 'Assert.Throws<T>(Func<Task>)'	UnitTests	C:\repos\pmcilreavy\AzureEventGridSimulator\src\UnitTests\Filtering\AdvancedFilterValidationTests.cs
* Error	The call is ambiguous between the following methods or properties: 'Assert.Throws<T>(Action)' and 'Assert.Throws<T>(Func<Task>)'	UnitTests	C:\repos\pmcilreavy\AzureEventGridSimulator\src\UnitTests\Filtering\AdvancedFilterValidationTests.cs
* Error	The call is ambiguous between the following methods or properties: 'Assert.Throws<T>(Action)' and 'Assert.Throws<T>(Func<Task>)'	UnitTests	C:\repos\pmcilreavy\AzureEventGridSimulator\src\UnitTests\Filtering\AdvancedFilterValidationTests.cs
* Error	The call is ambiguous between the following methods or properties: 'Assert.Throws<T>(Action)' and 'Assert.Throws<T>(Func<Task>)'	UnitTests	C:\repos\pmcilreavy\AzureEventGridSimulator\src\UnitTests\Filtering\AdvancedFilterValidationTests.cs
* Error	The call is ambiguous between the following methods or properties: 'Assert.Throws<T>(Action)' and 'Assert.Throws<T>(Func<Task>)'	UnitTests	C:\repos\pmcilreavy\AzureEventGridSimulator\src\UnitTests\Filtering\AdvancedFilterValidationTests.cs
* Error	The call is ambiguous between the following methods or properties: 'Assert.ThrowsAny<T>(Action)' and 'Assert.ThrowsAny<T>(Func<object>)'	UnitTests	C:\repos\pmcilreavy\AzureEventGridSimulator\src\UnitTests\Filtering\FilterSettingsValidationTests.cs

**Comment by pmcilreavy** [comment]
Compiles OK for me. Can you let me know what IDE and version you're using to compile it?

**Comment by uprightbass360** [comment]
Interesting! I am using Visual Studio Enterprise 2017 Version 15.9.14

**Comment by pmcilreavy** [comment]
Hmm that should be ok. I've just pushed a couple of changes and added a `build_and_test.bat` script which will `clean`, `build` and `test` the project using the `dotnet` command line tools if you want to give that a try and see if it works.

**Comment by pmcilreavy** [comment]
Closing this one as I believe it's compiling ok and could be a local setup issue.
