### ISSUE TITLE
Property 'Topic' was expected to either be null/empty.

### ISSUE THREAD

**Issue by klemmchr** [pmcilreavy/AzureEventGridSimulator#62]
When sending an event with a specified topic, I get the following error.

```
System.InvalidOperationException: Property 'Topic' was found to be set to 'Test', but was expected to either be null/empty.
    at AzureEventGridSimulator.Domain.Entities.EventGridEvent.Validate()
    at AzureEventGridSimulator.Infrastructure.Middleware.EventGridMiddleware.ValidateNotificationRequest(HttpContext context, SimulatorSettings simulatorSettings, SasKeyValidator sasHeaderValidator, ILogger logger)
```

Looking into the [code](https://github.com/pmcilreavy/AzureEventGridSimulator/blob/4dbaabd913e806424e259df55c67547f6acbe441/src/AzureEventGridSimulator/Domain/Entities/EventGridEvent.cs#L113) I can't really understand why Topic has to be null. Looking at the [docs of microsoft](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/messaging.eventgrid-readme-pre#publish-event-grid-events-to-an-event-grid-domain) it is totally fine to specify a topic in the event. I would understand that Event Grid Domains are not supported (which would be fine for me) but this validation seems incorrect. 
Before the event is being forwarded, the topic is being overriden in [`SendNotificationEventsToSubscriberCommandHandler.Handle`](https://github.com/pmcilreavy/AzureEventGridSimulator/blob/4dbaabd913e806424e259df55c67547f6acbe441/src/AzureEventGridSimulator/Domain/Commands/SendNotificationEventsToSubscriberCommandHandler.cs#L34) anyways, so why is the validation there in the first place?

**Comment by pmcilreavy** [comment]
Hi, you are only permitted to set the Topic when sending to an event grid domain endpoint. You will receive an error from a real event grid topic endpoint if you set the Topic field on the event, therefore the simulator also raises an error.
