### ISSUE TITLE
Pending Validation

### ISSUE THREAD

**Issue by dradovic** [pmcilreavy/AzureEventGridSimulator#79]
When I run the simulator with the `disableValidation` flag set to `true`, everything works as expected.

However, when I enable validation, I _never_ receive a POST request on the subscriber endpoint although the documentation says:
> The Azure Event Grid Simualator will mimick this validation behaviour at start up [...]

And  when an event is being published, the simulator log says:
> [09:45:22 WRN] Subscription '...' on topic '...' can't receive events. It's still pending validation

Is there something I'm missing here?

Thanks for providing this wonderful simulator.

**Comment by pmcilreavy** [comment]
Please can you re-test with the latest release. For me it seems ok.

**Comment by dradovic** [comment]
For me it's still not. Still the same behavior as described in the issue.

**Comment by dradovic** [comment]
BTW, I'm using the `pmcilreavy/azureeventgridsimulator:latest` docker image. Did you update that?

**Comment by pmcilreavy** [comment]
Ok, I can re-create it now. Hopefully get a fix out soon...in a day or so.

**Comment by pmcilreavy** [comment]
Ok, this should now be fixed if you pull the latest docker image.

**Comment by dradovic** [comment]
Yep, looks better now. Thanks again for sharing your work!
