### ISSUE TITLE
EventGridMiddleware.IsNotificationRequest: aeg-event-type is not mandatory with Event Grid

### ISSUE THREAD

**Issue by SimonLuckenuik** [pmcilreavy/AzureEventGridSimulator#9]
When I try to publish and event to the simulator without the aeg-event-type=Notification header, I get a Bad Request error code. This is not mandatory with Event Grid cloud service.

Ref: https://docs.microsoft.com/en-us/azure/event-grid/post-to-custom-topic

**Comment by pmcilreavy** [comment]
Fixed in release 1.0.51.

**Comment by SimonLuckenuik** [comment]
Wow, thank you for the quick response time :)
